---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "secret-data"
  name: secret-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "secret-data"
  strategy: {}
  template:
    metadata:
      labels:
        app: "secret-data"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 6464
      containers:
        - image: "busybox:latest"
          name: "busybox"
          resources:
            requests:
              cpu: "10m"
              memory: "24Mi"
            limits:
              cpu: "20m"
              memory: "32Mi"
          securityContext:
            readOnlyRootFilesystem: true
          env:
          - name: "SECRET_1"
            valueFrom:
              secretKeyRef:
                name: "secret-encoded-manual"
                key: "SECRET_1"
          command:
            - "/bin/sh"
            - "-c"
            - "while true; do echo \"SECRET_1=$SECRET_1\"; sleep 10; done"
...
