---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "deployment-basic.yaml"
  - "deployment-env.yaml"
  - "deployment-storage-emptydir.yaml"

  - "horizontalpodautoscaler.yaml"
  - "deployment-hpa.yaml"

  - "poddisruptionbudget.yaml"
  - "deployment-pdr.yaml"
...
